Welcome to the TestRepo wiki!
This repo is created for testing purposes, such as importing the wikis into another platform.
H1
Edit
H2
Edit
H3
H4
H5
H6
Alternatively, for H1 and H2, an underline-ish style:
Alt-H1
Edit
Alt-H2
Edit
Emphasis, aka italics, with asterisks or underscores.
Strong emphasis, aka bold, with asterisks or underscores.
Combined emphasis with asterisks and underscores.
Strikethrough uses two tildes. Scratch this.
First ordered list item
Another item ⋅⋅* Unordered sub-list.
Actual numbers don't matter, just that it's a number ⋅⋅1. Ordered sub-list
And another item.
⋅⋅⋅You can have properly indented paragraphs within list items. Notice the blank line above, and the leading spaces (at least one, but we'll use three here to also align the raw Markdown).
⋅⋅⋅To have a line break without a paragraph, you will need to use two trailing spaces.⋅⋅ ⋅⋅⋅Note that this line is separate, but within the same paragraph.⋅⋅ ⋅⋅⋅(This is contrary to the typical GFM line break behaviour, where trailing spaces are not required.)
Unordered list can use asterisks
Or minuses
Or pluses
I'm an inline-style link
I'm an inline-style link with title
I'm a reference-style link
I'm a relative reference to a repository file
You can use numbers for reference-style link definitions
Or leave it empty and use the link text itself.
URLs and URLs in angle brackets will automatically get turned into links. http://www.example.com or http://www.example.com and sometimes example.com (but not on Github, for example).
Some text to show that the reference links can follow later.
Here's our logo (hover to see the title text):
Inline-style:
Reference-style:
Inline Unknown macro: code. has Unknown macro: code. it.
Unknown macro: code.
Unknown macro: code.
Unknown macro: code.
Colons can be used to align columns.
Tables Are Cool
col 3 is right-aligned $1600
col 2 is centered $12
zebra stripes are neat $1
There must be at least 3 dashes separating each header cell. The outer pipes (|) are optional, and you don't need to make the raw Markdown line up prettily. You can also use inline Markdown.
Markdown Less Pretty
Still Unknown macro: code. nicely
1 2 3
Blockquotes are very handy in email to emulate reply text. This line is part of the same quote.
Quote break.
This is a very long line that will still be quoted properly when it wraps. Oh boy let's keep writing to make sure this is long enough to actually wrap for everyone. Oh, you can put Markdown into a blockquote.
Three or more...
Hyphens
Asterisks
Underscores